// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cTa3eiHE1m0Qt2PiC9lp6-n1jLEpPBA',
    appId: '1:981090665361:web:2981f911d104c6b935d030',
    messagingSenderId: '981090665361',
    projectId: 'storytelling-5a5b9',
    authDomain: 'storytelling-5a5b9.firebaseapp.com',
    storageBucket: 'storytelling-5a5b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6pljhmGUSoDl1WlUB--cDkoVHujaajw8',
    appId: '1:981090665361:android:de4538df1f4c435035d030',
    messagingSenderId: '981090665361',
    projectId: 'storytelling-5a5b9',
    storageBucket: 'storytelling-5a5b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAE1qardYrrIdu3CzChJ5Tqcq9_gV5WHg',
    appId: '1:981090665361:ios:788552e4f18a2e2e35d030',
    messagingSenderId: '981090665361',
    projectId: 'storytelling-5a5b9',
    storageBucket: 'storytelling-5a5b9.appspot.com',
    androidClientId: '981090665361-0pc88ukm6m63mht0o5efcrtuh8hk1u6f.apps.googleusercontent.com',
    iosClientId: '981090665361-q2pqqvgmaiillt1d4v13hok9n8sag3td.apps.googleusercontent.com',
    iosBundleId: 'com.example.storytelling',
  );
}
